import { DEFAULT_FOOTER_LINKS } from "@/lib/shared/config-parsers"
import { DEFAULT_SITE_HEADER_APP_LINKS } from "@/lib/site-header-app-links"
import { DEFAULT_MESSAGE_PROMPT_AUDIO_PATH } from "@/lib/message-prompt-audio"
import { DEFAULT_GOD_COMMENT_AUTO_LIKE_THRESHOLD } from "@/lib/god-comment-settings"

const defaultFooterCopyrightText = `Rhex 论坛系统 ${new Date().getFullYear()}`

export const defaultSiteSettingsCreateInput = {

  siteName: "Rhex 论坛系统",
  siteSlogan: "专注长期讨论与高质量交流",
  siteDescription: "Rhex 论坛系统是一个适合开源部署的现代论坛基础站点，默认提供可维护的正式初始化数据。",
  siteLogoText: "Rhex 论坛系统",
  siteLogoPath: null,
  siteSeoKeywords: "Rhex,Rhex 论坛系统,论坛,社区,Next.js,Prisma",
  pointName: "积分",
  footerLinksJson: JSON.stringify(DEFAULT_FOOTER_LINKS),
  analyticsCode: null,
  postLinkDisplayMode: "SLUG",
  homeFeedPostListDisplayMode: "DEFAULT",
  homeSidebarStatsCardEnabled: true,
  friendLinksEnabled: true,
  friendLinkApplicationEnabled: true,
  friendLinkAnnouncement: "欢迎与本站交换友情链接，请先添加我方链接后再提交申请，我们会在 1-3 个工作日内完成审核。",
  checkInEnabled: true,
  checkInReward: 5,
  checkInMakeUpCardPrice: 0,
  checkInVipMakeUpCardPrice: 0,
  postOfflinePrice: 0,
  postOfflineVip1Price: 0,
  postOfflineVip2Price: 0,
  postOfflineVip3Price: 0,
  inviteRewardInviter: 0,



  inviteRewardInvitee: 0,
  registrationEnabled: true,
  registrationRequireInviteCode: false,
  registerInviteCodeEnabled: true,
  inviteCodePurchaseEnabled: false,
  inviteCodePrice: 0,
  registerCaptchaMode: "OFF",
  loginCaptchaMode: "OFF",
  turnstileSiteKey: null,
  nicknameChangePointCost: 0,
  postEditableMinutes: 10,
  commentEditableMinutes: 5,
  godCommentAutoLikeThreshold: DEFAULT_GOD_COMMENT_AUTO_LIKE_THRESHOLD,
  tippingEnabled: false,
  tippingDailyLimit: 3,
  tippingPerPostLimit: 1,
  tippingAmounts: "10,30,50,100",
  postRedPacketEnabled: false,
  postRedPacketMaxPoints: 100,
  postRedPacketDailyLimit: 100,
  heatViewWeight: 1,
  heatCommentWeight: 8,
  heatLikeWeight: 6,
  heatTipCountWeight: 10,
  heatTipPointsWeight: 1,
  heatStageThresholds: "0,80,180,320,520,780,1100,1500,2000",
  heatStageColors: "#4A4A4A,#808080,#9B8F7F,#B87333,#C4A777,#E8C547,#FFA500,#D96C3B,#C41E3A",
  registerEmailEnabled: false,
  registerEmailRequired: false,
  registerEmailVerification: false,
  registerPhoneEnabled: false,
  registerPhoneRequired: false,
  registerPhoneVerification: false,
  registerNicknameEnabled: true,
  registerNicknameRequired: false,
  registerGenderEnabled: false,
  registerGenderRequired: false,
  registerInviterEnabled: true,
  smtpEnabled: false,
  smtpHost: null,
  smtpPort: null,
  smtpUser: null,
  smtpPass: null,
  smtpFrom: null,
  smtpSecure: false,
  vipMonthlyPrice: 3000,
  vipQuarterlyPrice: 8000,
  vipYearlyPrice: 30000,
  uploadProvider: "local",
  uploadLocalPath: "uploads",
  uploadBaseUrl: null,
  uploadOssBucket: null,
  uploadOssRegion: null,
  uploadOssEndpoint: null,
  uploadRequireLogin: true,
  uploadAllowedImageTypes: "jpg,jpeg,png,gif,webp",
  uploadMaxFileSizeMb: 5,
  uploadAvatarMaxFileSizeMb: 2,
  markdownEmojiMapJson: JSON.stringify([
    { shortcode: "smile", label: "微笑", icon: "😀", group: "默认" },
    { shortcode: "heart", label: "爱心", icon: "❤️", group: "默认" },
    { shortcode: "rocket", label: "火箭", icon: "🚀", group: "默认" },
    { shortcode: "fire", label: "火焰", icon: "🔥", group: "默认" },
    { shortcode: "sparkles", label: "闪光", icon: "✨", group: "默认" },
  ]),
  headerAppLinksJson: JSON.stringify(DEFAULT_SITE_HEADER_APP_LINKS),
  headerAppIconName: "grid",
  appStateJson: JSON.stringify({
    __siteSettings: {
      registerNicknameLengths: {
        minLength: 1,
        maxLength: 20,
      },
      passwordPolicy: {
        minLength: 6,
        strength: "LOW",
      },
      registerEmailWhitelist: {
        enabled: false,
        domains: [],
      },
      siteSecurity: {
        sessionIpMismatchLogoutEnabled: true,
        loginIpChangeEmailAlertEnabled: false,
        passwordChangeRequireEmailVerification: false,
      },
      checkInStreak: {
        enabled: true,
        makeUpCountsTowardStreak: true,
        oldestDayLimit: 0,
      },
      postSlugGeneration: {
        mode: "TITLE_TIMESTAMP",
      },
      siteBranding: {
        iconPath: "",
      },
      userProfile: {
        ipLocationEnabled: false,
      },
      footerCopyright: {
        text: defaultFooterCopyrightText,
        brandingVisible: true,
      },
      imageWatermark: {
        enabled: false,
        text: "",
        position: "BOTTOM_RIGHT",
        tiled: false,
        opacity: 22,
        fontSize: 24,
        fontFamily: "",
        margin: 24,
        color: "#FFFFFF",
      },
      registrationEmailTemplates: {
        registerVerification: {
          subject: "{{siteName}} 验证码",
          text: "你的验证码是 {{code}}，10 分钟内有效。如非本人操作请忽略。",
          html: "<div style=\"font-family:Arial,sans-serif;line-height:1.7;color:#111\"><h2>{{siteName}} 验证码</h2><p>你的验证码是：</p><p style=\"font-size:28px;font-weight:700;letter-spacing:6px\">{{code}}</p><p>验证码 10 分钟内有效，如非本人操作请忽略。</p></div>",
        },
        resetPasswordVerification: {
          subject: "{{siteName}} 找回密码验证码",
          text: "用户 {{username}} 的找回密码验证码是 {{code}}，10 分钟内有效。如非本人操作，请尽快检查账号安全。",
          html: "<div style=\"font-family:Arial,sans-serif;line-height:1.7;color:#111\"><h2>{{siteName}} 找回密码</h2><p>账号：<strong>{{username}}</strong></p><p>你的找回密码验证码是：</p><p style=\"font-size:28px;font-weight:700;letter-spacing:6px\">{{code}}</p><p>验证码 10 分钟内有效。如非本人操作，请忽略此邮件并尽快检查账号安全。</p></div>",
        },
        passwordChangeVerification: {
          subject: "{{siteName}} 修改密码验证码",
          text: "用户 {{username}} 的修改密码验证码是 {{code}}，10 分钟内有效。如非本人操作，请尽快检查账号安全。",
          html: "<div style=\"font-family:Arial,sans-serif;line-height:1.7;color:#111\"><h2>{{siteName}} 修改密码</h2><p>账号：<strong>{{username}}</strong></p><p>你的修改密码验证码是：</p><p style=\"font-size:28px;font-weight:700;letter-spacing:6px\">{{code}}</p><p>验证码 10 分钟内有效。如非本人操作，请忽略此邮件并尽快检查账号安全。</p></div>",
        },
        loginIpChangeAlert: {
          subject: "{{siteName}} 登录安全提醒",
          text: "{{displayName}}，你好。\n\n你的账号刚刚发生了一次新的登录，检测到登录 IP 与上次记录不一致。\n账号：{{username}}\n本次登录 IP：{{currentIp}}\n上次登录 IP：{{previousIp}}\n登录时间：{{loginAt}}\n设备信息：{{userAgent}}\n\n如果这是你本人操作，无需处理；如非本人操作，请尽快修改密码并检查账号安全。",
          html: "<div style=\"font-family:Arial,sans-serif;line-height:1.7;color:#111\"><h2>{{siteName}} 登录安全提醒</h2><p>{{displayName}}，你好。</p><p>你的账号刚刚发生了一次新的登录，检测到登录 IP 与上次记录不一致。</p><table style=\"border-collapse:collapse;margin:16px 0\"><tbody><tr><td style=\"padding:6px 12px 6px 0;color:#666\">账号</td><td style=\"padding:6px 0\">{{username}}</td></tr><tr><td style=\"padding:6px 12px 6px 0;color:#666\">本次登录 IP</td><td style=\"padding:6px 0\">{{currentIp}}</td></tr><tr><td style=\"padding:6px 12px 6px 0;color:#666\">上次登录 IP</td><td style=\"padding:6px 0\">{{previousIp}}</td></tr><tr><td style=\"padding:6px 12px 6px 0;color:#666\">登录时间</td><td style=\"padding:6px 0\">{{loginAt}}</td></tr><tr><td style=\"padding:6px 12px 6px 0;color:#666\">设备信息</td><td style=\"padding:6px 0\">{{userAgent}}</td></tr></tbody></table><p>如果这是你本人操作，无需处理；如非本人操作，请尽快修改密码并检查账号安全。</p></div>",
        },
        paymentOrderSuccessNotification: {
          subject: "{{siteName}} 支付成功通知 · {{orderSubject}}",
          text: "订单标题：{{orderSubject}}\n商户单号：{{merchantOrderNo}}\n业务场景：{{bizScene}}\n支付金额：{{amount}}\n支付方式：{{providerCode}} / {{channelCode}}\n支付时间：{{paidAt}}\n付款用户：{{username}}\n{{pointName}}到账：{{totalPoints}}",
          html: "<div style=\"font-family:Arial,sans-serif;line-height:1.7;color:#111\"><h2>{{siteName}} 支付成功通知</h2><p>订单标题：<strong>{{orderSubject}}</strong></p><table style=\"border-collapse:collapse;margin:16px 0\"><tbody><tr><td style=\"padding:6px 12px 6px 0;color:#666\">商户单号</td><td style=\"padding:6px 0\">{{merchantOrderNo}}</td></tr><tr><td style=\"padding:6px 12px 6px 0;color:#666\">业务场景</td><td style=\"padding:6px 0\">{{bizScene}}</td></tr><tr><td style=\"padding:6px 12px 6px 0;color:#666\">支付金额</td><td style=\"padding:6px 0\">{{amount}}</td></tr><tr><td style=\"padding:6px 12px 6px 0;color:#666\">支付方式</td><td style=\"padding:6px 0\">{{providerCode}} / {{channelCode}}</td></tr><tr><td style=\"padding:6px 12px 6px 0;color:#666\">支付时间</td><td style=\"padding:6px 0\">{{paidAt}}</td></tr><tr><td style=\"padding:6px 12px 6px 0;color:#666\">付款用户</td><td style=\"padding:6px 0\">{{username}}</td></tr><tr><td style=\"padding:6px 12px 6px 0;color:#666\">{{pointName}}到账</td><td style=\"padding:6px 0\">{{totalPoints}}</td></tr></tbody></table><p>如需追溯，请前往后台日志中心查看支付流水。</p></div>",
        },
      },
      authPageShowcase: {
        enabled: true,
      },
      smsProvider: {
        enabled: false,
        captchaMode: "OFF",
        aliyunEndpoint: "dysmsapi.aliyuncs.com",
        aliyunRegionId: "cn-hangzhou",
        aliyunSignName: "",
        aliyunTemplateCode: "",
        aliyunCodeParamName: "code",
      },
      emailBusinessSwitches: {
        registerVerification: true,
        resetPasswordVerification: true,
        passwordChangeVerification: true,
        loginIpChangeAlert: true,
        paymentOrderSuccess: true,
        lotteryWinner: true,
        systemNotification: true,
        privateMessage: true,
        addon: true,
      },
      leftSidebarDisplay: {
        mode: "DEFAULT",
      },
      leftSidebarHome: {
        enabled: true,
        name: "首页",
        icon: "🏠",
      },
      attachments: {
        uploadEnabled: false,
        downloadEnabled: false,
        minUploadLevel: 0,
        minUploadVipLevel: 0,
        allowedExtensions: ["zip", "rar", "7z", "pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "txt"],
        maxFileSizeMb: 20,
      },
      messageMedia: {
        enabled: true,
        imageUploadEnabled: false,
        fileUploadEnabled: false,
        promptAudioPath: DEFAULT_MESSAGE_PROMPT_AUDIO_PATH,
      },
      siteChat: {
        enabled: false,
      },
      commentAccess: {
        guestCanView: true,
        initialVisibleReplies: 10,
        loadMode: "PAGINATION",
      },
    },
  }),
  sensitiveStateJson: "{}",

} as const
