import type { AddonDefinition } from "@/addons-host/types"

export function defineAddon<TAddon extends AddonDefinition>(addon: TAddon) {
  return addon
}

export type {
  AddonActionHookContext,
  AddonActionHookName,
  AddonActionHookRegistration,
  AddonApiHandlerContext,
  AddonBackgroundJobApi,
  AddonBackgroundJobDeleteLocation,
  AddonBackgroundJobDeleteResult,
  AddonBackgroundJobEnqueueOptions,
  AddonBackgroundJobHandle,
  AddonBackgroundJobHandlerContext,
  AddonBackgroundJobRegistration,
  AddonDatabaseApi,
  AddonBadgeGrantInput,
  AddonBadgeGrantResult,
  AddonBadgeListOptions,
  AddonBadgeLookupInput,
  AddonBadgeSummary,
  AddonBadgesApi,
  AddonBoardSummary,
  AddonCommentCreateInput,
  AddonCommentCreateResult,
  AddonCommentLikeInput,
  AddonCommentLikeResult,
  AddonCommentQueryOptions,
  AddonCommentQueryResult,
  AddonCommentQuerySort,
  AddonCommentRecord,
  AddonCommentsApi,
  AddonDataCollectionDefinition,
  AddonDataMigrationRegistration,
  AddonDataQueryOptions,
  AddonDataQueryResult,
  AddonDataRecord,
  AddonEmailSendInput,
  AddonEmailSendResult,
  AddonEmailsApi,
  AddonApiRegistration,
  AddonApiResult,
  AddonAsyncWaterfallHookName,
  AddonAsyncWaterfallHookRegistration,
  AddonBuildApi,
  AddonDefinition,
  AddonInstallLifecycleContext,
  AddonLifecycleAction,
  AddonLifecycleContextBase,
  AddonLifecycleDatabaseApi,
  AddonLifecycleHooks,
  AddonManifest,
  AddonMessageSendInput,
  AddonMessageSendResult,
  AddonMessagesApi,
  AddonNotificationCreateInput,
  AddonNotificationRecord,
  AddonNotificationRelatedType,
  AddonNotificationsApi,
  AddonUninstallLifecycleContext,
  AddonUpgradeLifecycleContext,
  AddonPageRegistration,
  AddonPageChromeOptions,
  AddonPageRenderContext,
  AddonPageRenderResult,
  AddonPointAdjustInput,
  AddonPointAdjustResult,
  AddonPointsApi,
  AddonPostLikeInput,
  AddonPostLikeResult,
  AddonPostTipInput,
  AddonPostTipResult,
  AddonScheduledJobState,
  AddonScheduleEnsureOptions,
  AddonSchedulerApi,
  AddonScheduleStatus,
  AddonPostCreateInput,
  AddonPostCreateResult,
  AddonPostQueryOptions,
  AddonPostQueryResult,
  AddonPostQuerySort,
  AddonPostRecord,
  AddonPostStatusMode,
  AddonPostType,
  AddonPostsApi,
  AddonProviderRegistration,
  AddonReadableCommentStatus,
  AddonReadablePostStatus,
  AddonRenderResult,
  AddonSortDirection,
  AddonSlotProps,
  AddonFollowsApi,
  AddonUserFollowInput,
  AddonUserFollowResult,
  AddonUserSummary,
  AddonWaterfallHookContext,
  AddonWaterfallHookName,
  AddonWaterfallHookRegistration,
  AddonSlotKey,
  AddonSlotRegistration,
  AddonSlotRenderContext,
  AddonSurfaceKey,
  AddonSurfaceProps,
  AddonSurfaceRegistration,
  AddonSurfaceRenderContext,
  AddonZoneSummary,
} from "@/addons-host/types"
export type {
  AddonEditorComponentProps,
  AddonEditorProviderDescriptor,
  AddonEditorProviderRuntimeHooks,
  AddonEditorToolbarApi,
  AddonEditorToolbarItemComponentProps,
  AddonEditorToolbarItemDescriptor,
  AddonEditorToolbarItemRegistration,
  AddonEditorTarget,
} from "@/addons-host/editor-types"
export type {
  AddonEmojiProviderRuntimeHooks,
  ResolvedAddonEmojiItem,
} from "@/addons-host/emoji-types"
export type {
  AddonNavigationLink,
  AddonNavigationPlacement,
  AddonNavigationProviderRuntimeHooks,
  ResolvedAddonFooterLink,
  ResolvedAddonHeaderAppLink,
} from "@/addons-host/navigation-types"
export type {
  AddonAuthFieldValue,
  AddonAuthFields,
  AddonAuthLoginValidationInput,
  AddonAuthProviderRuntimeHooks,
  AddonAuthRegisterPayload,
  AddonAuthRegisterValidationInput,
  AddonAuthValidationResult,
} from "@/addons-host/auth-types"
export type {
  AddonCaptchaProviderRuntimeHooks,
  AddonCaptchaValidationResult,
  AddonLoginCaptchaValidationInput,
  AddonRegisterCaptchaValidationInput,
} from "@/addons-host/captcha-types"
export type {
  AddonUploadActor,
  AddonUploadPreparedFile,
  AddonUploadProviderRuntimeHooks,
  AddonUploadProviderSaveResult,
} from "@/addons-host/upload-types"
export type {
  AddonHomeFeedProviderMetadata,
  AddonHomeFeedProviderRenderInput,
  AddonHomeFeedProviderRuntimeHooks,
  AddonHomeFeedTabRegistration,
  ResolvedAddonHomeFeedTab,
} from "@/addons-host/home-feed-types"
